### PR TITLE
Completely Simplified Chinese translation for current docs.

### PR DESCRIPTION
**Pull request by Gitbreast**
---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [x] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [ ] 🙅 no documentation needed

### [optional] Are there any post-deployment tasks we need to perform?

You can publish it to the official Gitbook deployment. The old zh-CN intro is moved to  `zh-CN/use-cases` and referred to in `SUMMARY.md`. I used CAT tools to do the translation almost in the original format, which means most of the pics inside the docs are in HTML format (I changed the relative paths of course). I'm not very familiar with the Gitbook rule about HTML pic. If following the pics embedding in the original format doesn't work, just let me know.

### CODE REVIEW

**Comment by Gitbreast** [comment]
@d1eselboy

**Comment by fuksman** [comment]
@Gitbreast, thank you very much for you contribution!

**Comment by fuksman** [comment]
@any contributor @Gitbreast docs

**Comment by fuksman** [comment]
@any contributor @Gitbreast l10n

**Pull request merged**
